export const ErrorCodes = {
    VALIDATION_ERROR: "VALIDATION_ERROR",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};
